name: Flutter Android App CI/CD with Pgyer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: 🧰 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6'

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🔢 Bump version number
        run: dart tools/bump_version.dart

      # - name: 🛠 B Build APK
      #   run: flutter build apk --release

      - name: 📦 Upload APK to Pgyer
        run: cd tools/ && sh ./upload_to_pgyer.sh
        env:
          FIR_TOKEN: ${{ secrets.FIR_TOKEN }}