name: Flutter Android App CI/CD with Pgyer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: 🧰 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6'

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🔢 Bump version number
        run: dart tools/bump_version.dart

      - name: 🛠 Build APK
        id: build_apk
        run: |
          flutter build apk --release
          echo "apk_path=$(pwd)/build/app/outputs/flutter-apk/app-release.apk" >> $GITHUB_OUTPUT

      - name: 📦 Upload APK to Pgyer
        run: |
          echo "Uploading APK to Pgyer..."
          sh tools/upload_to_pgyer.sh
        env:
          FIR_TOKEN: ${{ secrets.FIR_TOKEN }}
          APK_PATH: ${{ steps.build_apk.outputs.apk_path }}
          