name: Flutter Android App CI/CD with Pgyer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: 🧰 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6'

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🔢 Bump version number
        run: dart tools/bump_version.dart

      - name: 🛠 Build APK
        id: build_apk
        run: |
          flutter build apk --release
          echo "apk_path=$(pwd)/build/app/outputs/flutter-apk/app-release.apk" >> $GITHUB_OUTPUT

      - name: Download go-fir-cli
        run: |
          echo "Downloading go-fir-cli..."
          curl -L https://github.com/PGYER/go-fir-cli/releases/download/0.0.10/go-fir-cli-0.0.10-linux-amd64.tar.gz | tar xz -C tools
          chmod +x tools/go-fir-cli
          file tools/go-fir-cli

      - name: 📦 Upload APK to Pgyer
        run: |
          echo "Uploading APK to Pgyer..."
          tools/go-fir-cli login -t a7d3b217e7132bd0b79ffa45f35651b3
          tools/go-fir-cli upload -f ${{ steps.build_apk.outputs.apk_path }}
      #     bash tools/pgyer_upload.sh -k a7d3b217e7132bd0b79ffa45f35651b3 ${{ steps.build_apk.outputs.apk_path }}